### ISSUE TITLE
Trying to run on macOS

### ISSUE THREAD

**Issue by tsaulic** [xyzz/pob-web#1]
So far, I had to tweak some things to try run this on macOS.

In prepare.sh I had to add

```mkdir -p PathOfBuilding/Assets``` along with TreeData

and I had to create a /etc/mime.types file containing the ```application/wasm    wasm``` line for Python HTTP server to not complain about the MIME type

But, when I do everything and compile successfully with ```make clean && make -j8```

Spinning up the server and hitting index.html results in ```PANIC: unprotected error in call to Lua API (cannot open Launch.lua: No such file or directory)```

Any idea what the issue is here? Apparently it's referenced from pob.wasm, and I tried to include it in output/PathOfBuilding, but that didn't do anything.

Any help is appreciated.

**Comment by xyzz** [comment]
I've updated it for osx, please try again.

**Comment by tsaulic** [comment]
You are da man! :) works

Also for anyone else that may try to do this on macOS, create a /etc/mime.types file containing the application/wasm wasm line for Python HTTP server to not complain about the MIME type.
The file in _download will be downloaded as some Amazon generated file name, you have to rename to 'PathOfBuilding-1.4.67.zip' (or whatever the version is when you use this tool).

Thanks again, this is amazing!
